apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: colossus-data-deployment
  labels:
    app: colossus
spec:
  selector:
    matchLabels:
      app: colossus
  replicas: 3
  template:
    metadata:
      labels:
        app: colossus
    spec:
      containers:
        - name: colossus-data
          image: colossus/data
          ports:
          - containerPort: 1111
---
apiVersion: v1
kind: Service
metadata:
  name: colossus-data-svc
spec:
  selector:
    app: colossus
  ports:
  - name: http
    protocol: TCP
    port: 1111
    targetPort: 1111
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: colossus-auth-deployment
  labels:
    app: colossus
spec:
  selector:
    matchLabels:
      app: colossus
  replicas: 3
  template:
    metadata:
      labels:
        app: colossus
    spec:
      containers:
        - name: colossus-auth
          image: colossus/auth
          ports:
            - containerPort: 8888
---
apiVersion: v1
kind: Service
metadata:
  name: colossus-auth-svc
spec:
  selector:
    app: colossus
  ports:
    - name: http
      protocol: TCP
      port: 8888
      targetPort: 8888
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: colossus-userinfo-deployment
  labels:
    app: colossus
spec:
  selector:
    matchLabels:
      app: colossus
  replicas: 3
  template:
    metadata:
      labels:
        app: colossus
    spec:
      containers:
        - name: colossus-userinfo
          image: colossus/userinfo
          ports:
            - containerPort: 7777
---
apiVersion: v1
kind: Service
metadata:
  name: colossus-userinfo-svc
spec:
  selector:
    app: colossus
  ports:
    - name: http
      protocol: TCP
      port: 7777
      targetPort: 7777
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: colossus-web-deployment
  labels:
    app: colossus
spec:
  selector:
    matchLabels:
      app: colossus
  replicas: 3
  template:
    metadata:
      labels:
        app: colossus
    spec:
      containers:
        - name: colossus-web
          image: colossus/web
          ports:
            - containerPort: 3000
          env:
          - name: AUTH_SERVICE_PORT
            value: '8888'
          - name: AUTH_SERVICE_HOST
            value: colossus-auth-svc
          - name: DATA_SERVICE_PORT
            value: '1111'
          - name: DATA_SERVICE_HOST
            value: colossus-data-svc
          - name: USERINFO_SERVICE_PORT
            value: '7777'
          - name: USERINFO_SERVICE_HOST
            value: colossus-userinfo-svc
---
apiVersion: v1
kind: Service
metadata:
  name: colossus-web-svc
spec:
  selector:
    app: colossus
  ports:
    - name: http
      protocol: TCP
      port: 3000
      targetPort: 3000
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: colossus-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  backend:
    serviceName: colossus-web-svc
    servicePort: 3000
---
apiVersion: v1
kind: Pod
metadata:
  name: busybox
spec:
  containers:
  - name: busybox
    image: busybox
    args:
    - sh
    - -c
    - tail -f /dev/null
